/**
 * RiskExplanation.tsx  —  NEW FILE (no existing files modified)
 *
 * A self-contained React component that renders an AI-generated, human-readable
 * explanation of the current risk score for a zone.
 *
 * ── Usage ────────────────────────────────────────────────────────────────────
 *
 *   import { RiskExplanation } from '../components/RiskExplanation'
 *
 *   // Inside ZoneDetailPage, ZoneDrilldown, or any card:
 *   <RiskExplanation zone={zone} permits={permits} alerts={alerts} />
 *
 * ── What it renders ──────────────────────────────────────────────────────────
 *
 *   ┌─────────────────────────────────────────────────────────┐
 *   │  🤖  AI Risk Advisor              [Generated by Gemini] │
 *   │ ─────────────────────────────────────────────────────── │
 *   │  "Risk in Zone 4 – Compressor Bay is at a critical      │
 *   │   level (84/100) because a hot-work permit is active,   │
 *   │   a critical alert has been raised: 'Gas concentration  │
 *   │   exceeding threshold', and the zone is classified as   │
 *   │   a gas hazard area."                                   │
 *   └─────────────────────────────────────────────────────────┘
 *
 * No existing file is modified.  Simply import and drop it wherever needed.
 */
import React, { useEffect, useRef, useState } from 'react'
import type { Alert, Permit, Zone } from '../types'
import { useRiskExplanation } from '../hooks/useRiskExplanation'

// ── Icon helpers (inline SVG, no extra dependencies) ─────────────────────────

const BrainIcon = () => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={16}
    height={16}
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth={2}
    strokeLinecap="round"
    strokeLinejoin="round"
    aria-hidden="true"
  >
    <path d="M9.5 2A2.5 2.5 0 0 1 12 4.5v15a2.5 2.5 0 0 1-4.96-.46 2.5 2.5 0 0 1-1.07-4.69 3 3 0 0 1 .79-5.81h.01A2.5 2.5 0 0 1 9.5 2Z" />
    <path d="M14.5 2A2.5 2.5 0 0 0 12 4.5v15a2.5 2.5 0 0 0 4.96-.46 2.5 2.5 0 0 0 1.07-4.69 3 3 0 0 0-.79-5.81h-.01A2.5 2.5 0 0 0 14.5 2Z" />
  </svg>
)

const SparkleIcon = () => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={11}
    height={11}
    viewBox="0 0 24 24"
    fill="currentColor"
    aria-hidden="true"
  >
    <path d="M12 2l2.4 7.2L22 12l-7.6 2.8L12 22l-2.4-7.2L2 12l7.6-2.8L12 2z" />
  </svg>
)

// ── Animated typing cursor ────────────────────────────────────────────────────

function BlinkingCursor() {
  return (
    <span
      aria-hidden="true"
      style={{
        display: 'inline-block',
        width: 2,
        height: '1em',
        background: 'currentColor',
        marginLeft: 2,
        verticalAlign: 'text-bottom',
        animation: 'sg-blink 1s step-end infinite',
      }}
    />
  )
}

// ── Loading skeleton ──────────────────────────────────────────────────────────

function ExplanationSkeleton() {
  return (
    <div role="status" aria-label="Generating risk explanation…">
      {[90, 100, 78].map((w, i) => (
        <div
          key={i}
          className="skeleton"
          style={{
            height: 12,
            width: `${w}%`,
            marginBottom: i < 2 ? 8 : 0,
            borderRadius: 6,
          }}
        />
      ))}
    </div>
  )
}

// ── Animated text reveal ──────────────────────────────────────────────────────

function AnimatedText({ text }: { text: string }) {
  const [displayed, setDisplayed] = useState('')
  const [done, setDone] = useState(false)
  const prevText = useRef('')

  useEffect(() => {
    if (text === prevText.current) return
    prevText.current = text
    setDisplayed('')
    setDone(false)

    let i = 0
    // Use a fast "typewriter" effect — character per frame, ~30 chars/s
    const interval = setInterval(() => {
      i += 2
      if (i >= text.length) {
        setDisplayed(text)
        setDone(true)
        clearInterval(interval)
      } else {
        setDisplayed(text.slice(0, i))
      }
    }, 18)

    return () => clearInterval(interval)
  }, [text])

  return (
    <span>
      {displayed}
      {!done && <BlinkingCursor />}
    </span>
  )
}

// ── Risk-level pill ───────────────────────────────────────────────────────────

const LEVEL_STYLES: Record<string, { bg: string; text: string; label: string }> = {
  critical: { bg: 'rgba(248,81,73,0.12)', text: 'var(--color-critical)',  label: 'Critical' },
  warning:  { bg: 'rgba(230,162,62,0.12)',  text: 'var(--color-warning)',   label: 'Warning'  },
  watch:    { bg: 'rgba(88,166,255,0.12)',  text: 'var(--color-watch)',     label: 'Watch'    },
  low:      { bg: 'rgba(63,185,80,0.12)',   text: 'var(--color-success)',   label: 'Low Risk' },
}

function RiskPill({ level }: { level: string }) {
  const s = LEVEL_STYLES[level] ?? LEVEL_STYLES.low
  return (
    <span
      style={{
        display: 'inline-flex',
        alignItems: 'center',
        gap: 4,
        padding: '2px 8px',
        borderRadius: 999,
        background: s.bg,
        color: s.text,
        fontSize: 11,
        fontWeight: 700,
        textTransform: 'uppercase',
        letterSpacing: '0.05em',
      }}
    >
      <span
        style={{
          width: 5,
          height: 5,
          borderRadius: '50%',
          background: s.text,
          flexShrink: 0,
        }}
      />
      {s.label}
    </span>
  )
}

// ── Main component ────────────────────────────────────────────────────────────

interface RiskExplanationProps {
  zone: Zone
  permits?: Permit[]
  alerts?: Alert[]
  /** Optional: collapse to one line by default and expand on click */
  collapsible?: boolean
  className?: string
  style?: React.CSSProperties
}

export function RiskExplanation({
  zone,
  permits = [],
  alerts = [],
  collapsible = false,
  className,
  style,
}: RiskExplanationProps) {
  const { explanation, riskLevel, loading, error, generatedBy } =
    useRiskExplanation(zone, permits, alerts)

  const [expanded, setExpanded] = useState(!collapsible)

  // Inject keyframe animation once into the document
  useEffect(() => {
    const id = 'sg-risk-explain-styles'
    if (document.getElementById(id)) return
    const style = document.createElement('style')
    style.id = id
    style.textContent = `
      @keyframes sg-blink {
        0%, 100% { opacity: 1; }
        50%       { opacity: 0; }
      }
      @keyframes sg-fade-in {
        from { opacity: 0; transform: translateY(4px); }
        to   { opacity: 1; transform: translateY(0);   }
      }
      .sg-risk-explain-panel {
        animation: sg-fade-in 0.35s ease both;
      }
    `
    document.head.appendChild(style)
  }, [])

  const accentColor = riskLevel
    ? (LEVEL_STYLES[riskLevel]?.text ?? 'var(--color-accent)')
    : 'var(--color-accent)'

  return (
    <div
      id={`risk-explain-${zone.id}`}
      className={`card sg-risk-explain-panel${className ? ` ${className}` : ''}`}
      style={{
        padding: '16px 18px',
        border: `1px solid ${accentColor}28`,
        position: 'relative',
        overflow: 'hidden',
        ...style,
      }}
    >
      {/* Subtle top-left accent glow */}
      <div
        aria-hidden="true"
        style={{
          position: 'absolute',
          top: 0,
          left: 0,
          width: 120,
          height: 60,
          background: `radial-gradient(ellipse at 0% 0%, ${accentColor}18 0%, transparent 70%)`,
          pointerEvents: 'none',
        }}
      />

      {/* Header row */}
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          gap: 8,
          marginBottom: loading || explanation ? 12 : 0,
          cursor: collapsible ? 'pointer' : 'default',
        }}
        onClick={collapsible ? () => setExpanded(v => !v) : undefined}
        role={collapsible ? 'button' : undefined}
        tabIndex={collapsible ? 0 : undefined}
        aria-expanded={collapsible ? expanded : undefined}
        onKeyDown={collapsible ? (e) => { if (e.key === 'Enter' || e.key === ' ') setExpanded(v => !v) } : undefined}
      >
        <div style={{ display: 'flex', alignItems: 'center', gap: 7 }}>
          <div
            style={{
              width: 28,
              height: 28,
              borderRadius: 8,
              background: `${accentColor}18`,
              color: accentColor,
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              flexShrink: 0,
            }}
          >
            <BrainIcon />
          </div>
          <div>
            <div
              style={{
                fontSize: 12,
                fontWeight: 700,
                color: 'var(--color-text-primary)',
                letterSpacing: '0.01em',
              }}
            >
              AI Risk Advisor
            </div>
            {riskLevel && !loading && (
              <div style={{ marginTop: 2 }}>
                <RiskPill level={riskLevel} />
              </div>
            )}
          </div>
        </div>

        {/* "Generated by" badge */}
        {generatedBy && !loading && (
          <div
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: 4,
              padding: '3px 8px',
              borderRadius: 999,
              background: 'var(--color-surface)',
              border: '1px solid var(--color-border)',
              fontSize: 10,
              fontWeight: 600,
              color: 'var(--color-text-muted)',
              textTransform: 'uppercase',
              letterSpacing: '0.06em',
              flexShrink: 0,
            }}
          >
            <SparkleIcon />
            {generatedBy === 'llm' ? 'Gemini' : 'Rule-based'}
          </div>
        )}
      </div>

      {/* Body */}
      {(expanded || !collapsible) && (
        <div>
          {/* Divider */}
          <div
            style={{
              height: 1,
              background: `linear-gradient(to right, ${accentColor}40, transparent)`,
              marginBottom: 12,
            }}
          />

          {loading && <ExplanationSkeleton />}

          {!loading && error && (
            <div
              role="alert"
              style={{
                fontSize: 13,
                color: 'var(--color-text-secondary)',
                fontStyle: 'italic',
              }}
            >
              Unable to generate explanation: {error}
            </div>
          )}

          {!loading && !error && explanation && (
            <p
              style={{
                margin: 0,
                fontSize: 13,
                lineHeight: 1.65,
                color: 'var(--color-text-primary)',
              }}
            >
              <AnimatedText text={explanation} />
            </p>
          )}

          {!loading && !error && !explanation && (
            <div
              style={{
                fontSize: 13,
                color: 'var(--color-text-muted)',
                fontStyle: 'italic',
              }}
            >
              Waiting for score data…
            </div>
          )}
        </div>
      )}
    </div>
  )
}
