import json
from typing import Dict, Any
from datetime import datetime

class ComplianceReportService:
    """
    Extracts data signatures from an alert's graph_path and fills an OISD/DGMS 
    statutory submission template (PDF/HTML generation).
    """
    
    def generate_report_html(self, alert_id: str, alert_data: Dict[str, Any], audit_violations: list) -> str:
        """
        Generates a structured HTML report that can be converted to PDF.
        """
        now_str = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")
        
        html_template = f"""
        <html>
        <head>
            <style>
                body {{ font-family: Arial, sans-serif; line-height: 1.6; margin: 40px; }}
                h1 {{ color: #b30000; border-bottom: 2px solid #b30000; padding-bottom: 5px; }}
                h2 {{ color: #333; margin-top: 30px; }}
                .meta {{ background: #f4f4f4; padding: 15px; border-radius: 5px; }}
                .violation {{ background: #fff3f3; border-left: 4px solid #cc0000; padding: 10px; margin-bottom: 10px; }}
                .graph-data {{ background: #f0f8ff; padding: 15px; font-family: monospace; white-space: pre-wrap; }}
            </style>
        </head>
        <body>
            <h1>SentinelGrid: Statutory Incident / Near-Miss Report</h1>
            
            <div class="meta">
                <p><strong>Report ID:</strong> {alert_id}</p>
                <p><strong>Generated At:</strong> {now_str}</p>
                <p><strong>Severity:</strong> {alert_data.get('severity', 'UNKNOWN').upper()}</p>
                <p><strong>Zone ID:</strong> {alert_data.get('zone_id', 'UNKNOWN')}</p>
            </div>
            
            <h2>1. Incident Summary</h2>
            <p>An automated safety halt was triggered due to compound risk detection.</p>
            
            <h2>2. Regulatory Violations Detected</h2>
        """
        
        if not audit_violations:
            html_template += "<p>No explicit statutory rule violations detected (preventative trigger).</p>"
        else:
            for v in audit_violations:
                html_template += f"""
                <div class="violation">
                    <p><strong>Rule:</strong> {v.get('rule')}</p>
                    <p><strong>Violation:</strong> {v.get('violation')}</p>
                    <p><strong>Corrective Action:</strong> {v.get('corrective_action')}</p>
                </div>
                """
                
        html_template += """
            <h2>3. Automated Graph Evidence Snapshot</h2>
            <div class="graph-data">
        """
        
        # Dump graph path as formatted JSON for evidence
        html_template += json.dumps(alert_data.get("graph_path", {}), indent=2)
        
        html_template += """
            </div>
            
            <p style="margin-top: 40px; font-size: 12px; color: #888;">
                * This report is auto-generated by the SentinelGrid Compliance Audit Agent.
            </p>
        </body>
        </html>
        """
        
        return html_template
        
compliance_report_service = ComplianceReportService()
