import re
from typing import List, Dict, Any

class CitationGuard:
    """
    Final security guardrail that prevents text hallucinations.
    Regex interceptor engine that string-matches any clause number or document signature generated by the LLM 
    against the source metadata array of the top 3 retrieved context blocks.
    """
    def __init__(self):
        # Look for typical citation patterns: Section X, Clause Y, INC-YYYY-MM-DD
        self.citation_pattern = re.compile(r'(Section\s+\d+|Clause\s+\d+|OISD-STD-\d+|INC-\d{4}-\d{2}-\d{2})', re.IGNORECASE)

    def verify_citations(self, llm_response: str, context_chunks: List[Dict[str, Any]]) -> bool:
        """
        Returns True if all citations found in the LLM response are present in the provided context texts.
        Returns False if a hallucinated citation is detected.
        """
        # If the LLM successfully refused, it's valid
        if "I cannot answer based on verified data" in llm_response:
            return True
            
        found_citations = self.citation_pattern.findall(llm_response)
        
        if not found_citations:
            # No specific citations made, we'll let it pass (or you could enforce mandatory citations)
            return True
            
        # Combine all allowed text and metadata for simple string matching
        allowed_text = ""
        for chunk in context_chunks:
            allowed_text += chunk["payload"]["text"] + " "
            allowed_text += str(chunk["payload"].get("document_id", "")) + " "
            
        allowed_text = allowed_text.lower()
        
        for citation in found_citations:
            # Simple substring check - if the cited section/incident isn't anywhere in the retrieved text, reject
            if citation.lower() not in allowed_text:
                print(f"HALLUCINATION GUARD: Unverified citation detected -> '{citation}'")
                return False
                
        return True
